import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const LAST_UPDATED = "January 1, 2026";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-4xl mx-auto w-full px-4 sm:px-6 py-12">
        <h1 className="text-3xl font-extrabold text-slate-800 mb-2">Privacy &amp; Policy</h1>
        <p className="text-blue-600 font-medium mb-1">All Yono Games</p>
        <p className="text-slate-400 text-xs mb-8">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-6">

          {/* Intro */}
          <div className="bg-white rounded-2xl border border-blue-100 shadow-sm p-6 text-slate-600 text-sm leading-relaxed">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="mt-3">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Interpretation */}
          <Section title="Interpretation and Definitions">
            <h3 className="font-bold text-slate-700 mb-2">Interpretation</h3>
            <p className="mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
            <h3 className="font-bold text-slate-700 mb-2">Definitions</h3>
            <p className="mb-3">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-2">
              <DefItem term="Account">means a unique account created for You to access our Service or parts of our Service.</DefItem>
              <DefItem term="Affiliate">means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</DefItem>
              <DefItem term="Company">(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <strong>AllYonoGames</strong>.</DefItem>
              <DefItem term="Cookies">are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</DefItem>
              <DefItem term="Country">refers to: <strong>India</strong></DefItem>
              <DefItem term="Device">means any device that can access the Service such as a computer, a cellphone or a digital tablet.</DefItem>
              <DefItem term="Personal Data">is any information that relates to an identified or identifiable individual.</DefItem>
              <DefItem term="Service">refers to the Website.</DefItem>
              <DefItem term="Service Provider">means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</DefItem>
              <DefItem term="Usage Data">refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</DefItem>
              <DefItem term="Website">refers to AllYonoGames, accessible from <a href="https://allyonoogames.com" className="text-blue-600 underline hover:text-blue-800">https://allyonoogames.com</a></DefItem>
              <DefItem term="You">means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</DefItem>
            </ul>
          </Section>

          {/* Collecting */}
          <Section title="Collecting and Using Your Personal Data">
            <h3 className="font-bold text-slate-700 mb-2">Types of Data Collected</h3>
            <h4 className="font-semibold text-slate-600 mb-1">Personal Data</h4>
            <p className="mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Usage Data.
            </p>
            <h4 className="font-semibold text-slate-600 mb-1">Usage Data</h4>
            <p className="mb-3">Usage Data is collected automatically when using the Service.</p>
            <p className="mb-3">
              Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="mb-3">
              When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
            <p>
              We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
            </p>
          </Section>

          {/* Cookies */}
          <Section title="Tracking Technologies and Cookies">
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
            </p>
            <ul className="space-y-3 mb-4">
              <li className="flex gap-2">
                <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400" />
                <span><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</span>
              </li>
              <li className="flex gap-2">
                <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400" />
                <span><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email and for other related website statistics.</span>
              </li>
            </ul>
            <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
            <div className="space-y-3">
              {[
                { type: "Necessary / Essential Cookies", cookieType: "Session Cookies", admin: "Us", purpose: "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts." },
                { type: "Cookies Policy / Notice Acceptance Cookies", cookieType: "Persistent Cookies", admin: "Us", purpose: "These Cookies identify if users have accepted the use of cookies on the Website." },
                { type: "Functionality Cookies", cookieType: "Persistent Cookies", admin: "Us", purpose: "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference." },
              ].map((c) => (
                <div key={c.type} className="bg-blue-50 rounded-xl p-4">
                  <p className="font-semibold text-slate-700 text-sm">{c.type}</p>
                  <p className="text-xs text-slate-500 mt-1">Type: {c.cookieType} &nbsp;|&nbsp; Administered by: {c.admin}</p>
                  <p className="text-xs text-slate-600 mt-1">{c.purpose}</p>
                </div>
              ))}
            </div>
          </Section>

          {/* Use of data */}
          <Section title="Use of Your Personal Data">
            <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-2 mb-4">
              {[
                "To provide and maintain our Service, including to monitor the usage of our Service.",
                "To manage Your Account: to manage Your registration as a user of the Service.",
                "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.",
                "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.",
                "To provide You with news, special offers and general information about other goods, services and events which we offer.",
                "To manage Your requests: To attend and manage Your requests to Us.",
                "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.",
                "For other purposes: such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.",
              ].map((item, i) => (
                <li key={i} className="flex gap-2">
                  <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-3">We may share Your personal information in the following situations:</p>
            <ul className="space-y-2">
              {[
                { bold: "With Service Providers:", text: "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You." },
                { bold: "For business transfers:", text: "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition." },
                { bold: "With Affiliates:", text: "We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy." },
                { bold: "With business partners:", text: "We may share Your information with Our business partners to offer You certain products, services or promotions." },
                { bold: "With other users:", text: "when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users." },
                { bold: "With Your consent:", text: "We may disclose Your personal information for any other purpose with Your consent." },
              ].map((item, i) => (
                <li key={i} className="flex gap-2">
                  <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400" />
                  <span><strong>{item.bold}</strong> {item.text}</span>
                </li>
              ))}
            </ul>
          </Section>

          {/* Retention */}
          <Section title="Retention of Your Personal Data">
            <p className="mb-3">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p>
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.
            </p>
          </Section>

          {/* Transfer */}
          <Section title="Transfer of Your Personal Data">
            <p className="mb-3">
              Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
            </p>
            <p className="mb-3">
              Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            </p>
            <p>
              The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
            </p>
          </Section>

          {/* Delete */}
          <Section title="Delete Your Personal Data">
            <p className="mb-3">
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
            </p>
            <p className="mb-3">
              Our Service may give You the ability to delete certain information about You from within the Service.
            </p>
            <p className="mb-3">
              You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
            </p>
            <p>
              Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
            </p>
          </Section>

          {/* Disclosure */}
          <Section title="Disclosure of Your Personal Data">
            <h3 className="font-bold text-slate-700 mb-2">Business Transactions</h3>
            <p className="mb-4">
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
            </p>
            <h3 className="font-bold text-slate-700 mb-2">Law Enforcement</h3>
            <p className="mb-4">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
            </p>
            <h3 className="font-bold text-slate-700 mb-2">Other Legal Requirements</h3>
            <p className="mb-2">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="space-y-1.5">
              {[
                "Comply with a legal obligation",
                "Protect and defend the rights or property of the Company",
                "Prevent or investigate possible wrongdoing in connection with the Service",
                "Protect the personal safety of Users of the Service or the public",
                "Protect against legal liability",
              ].map((item, i) => (
                <li key={i} className="flex gap-2">
                  <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </Section>

          {/* Security */}
          <Section title="Security of Your Personal Data">
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </Section>

          {/* Children */}
          <Section title="Children's Privacy">
            <p className="mb-3">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
            </p>
            <p>
              If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.
            </p>
          </Section>

          {/* Links */}
          <Section title="Links to Other Websites">
            <p className="mb-3">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p>
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>
          </Section>

          {/* Changes */}
          <Section title="Changes to this Privacy Policy">
            <p className="mb-3">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="mb-3">
              We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
          </Section>

          {/* Contact */}
          <div className="bg-blue-600 rounded-2xl p-6 text-white">
            <h2 className="font-bold text-xl mb-3">Contact Us</h2>
            <p className="text-blue-100 text-sm mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <a
              href="mailto:support@AllYonoGames.com"
              className="inline-flex items-center gap-2 bg-white text-blue-700 font-semibold text-sm px-5 py-2.5 rounded-xl hover:bg-blue-50 transition-colors duration-200"
            >
              📧 support@AllYonoGames.com
            </a>
          </div>

        </div>
      </main>
      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="bg-white rounded-2xl border border-blue-100 shadow-sm p-6">
      <h2 className="text-slate-800 font-bold text-lg mb-3 pb-2 border-b border-blue-50">{title}</h2>
      <div className="text-slate-600 text-sm leading-relaxed">{children}</div>
    </div>
  );
}

function DefItem({ term, children }: { term: string; children: React.ReactNode }) {
  return (
    <li className="flex gap-2">
      <span className="shrink-0 mt-1.5 w-1.5 h-1.5 rounded-full bg-blue-400" />
      <span><strong className="text-slate-700">{term}</strong> — {children}</span>
    </li>
  );
}
